### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by PNPyrenees** [PNPyrenees/app_carto#1]
- [x] Assurer l'authentification des utilisateurs via GeoNature
- [x] Permettre à l'utilisateur d'afficher des couche de référence
- [x] Permettre à l'utilisateur d'interroger les données d'observation
- [x] Permettre l'export de carte en PDF
- [x] Développer la fonction de calcul des enjeux sur un périmètre dessiné sur la carte
- [x] Localiser un toponyme
- [x] Permettre à l'utilisateur de dessiner des objets (trait, rond, rectangle...) sur la carte 
- [ ] Permettre d'ajouter des couches au format GeoTiff
- [x] Permettre à l'utilisateur de modifier le style d'une couche
- [ ] Permettre à l'utilisateur de créer des projets (enregistrement des couches affiché, leur style et leur état)
- [ ] Permettre à l'utilisateur de créer des couches de données
- [ ] Mettre en place un système permettant à une utilisateur de partager ses couches (lecture/ecriture) avec d'autres utilisateurs (ainsi que des projets)
- [ ] Développer une interface d'administration permettant de déclarer une nouvelle couche et de définir le style par défaut
- [ ] Produire un script d'installation (et de mise à jour)
- [ ] ...
